# Generated by Django 4.2.13 on 2024-07-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('U_Auth', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_technician',
        ),
    ]
