# Generated by Django 4.2.13 on 2024-07-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_Auth', '0004_rename_is_employee_user_is_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
