# Generated by Django 4.2.13 on 2024-07-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_Auth', '0005_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
