# Generated by Django 5.0.6 on 2024-07-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.IntegerField(default=1)),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
    ]
