# Generated by Django 5.0.6 on 2024-06-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='Phone',
            new_name='Mobile',
        ),
    ]
