# Generated by Django 5.0.6 on 2024-06-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_rename_phone_site_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='Mobile',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='Place',
            new_name='Location',
        ),
    ]
