# Generated by Django 5.0.6 on 2024-06-27 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_rename_mobile_site_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.IntegerField(default=1)),
                ('Title', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.IntegerField(default=1)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField(null=True)),
                ('Amount', models.FloatField(default=0.0)),
                ('Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.transaction_category')),
            ],
        ),
    ]
