# Generated by Django 5.0.6 on 2024-06-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_transaction_category_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Type',
            new_name='Category',
        ),
    ]
