# Generated by Django 5.0.6 on 2024-07-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Number', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Description', models.TextField()),
            ],
        ),
    ]
