# Generated by Django 5.0.6 on 2024-07-08 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecall',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecall',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
